service: s3-sitemap

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: iiif-serverless-s3-sitemap

functions:
  sitemap:
    handler: sitemap.update
    events:
        - httpApi:
            path: /
            method: post

plugins:
  - serverless-offline
  - serverless-python-requirements
