service: s3-sitemap

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: iiif-serverless-s3-sitemap
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:*Object*'
          Resource:
            - 'arn:aws:s3:::iiif-website/*'
            - 'arn:aws:s3:::training.iiif.io/*'
        - Effect: 'Allow'
          Action:
            - 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::iiif-website'
            - 'arn:aws:s3:::training.iiif.io'
        - Effect: 'Allow'
          Action:
            - 'logs:CreateLogStream'
            - 'logs:CreateLogGroup'
            - 'logs:PutLogEvents'
          Resource:
            - 'arn:aws:logs:us-east-1:420715881449:log-group:/aws/lambda/s3-sitemap:*'

functions:
  sitemap:
    handler: sitemap.update
    events:
        - httpApi:
            path: /
            method: post

plugins:
  - serverless-offline
  - serverless-python-requirements
