service: s3-sitemap

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  deploymentBucket:
    name: iiif-serverless-s3-sitemap
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 's3:PutObject'
            - 's3:GetObject'
            - 's3:GetObjectVersion'
            - 's3:ListBucket'
          Resource:
            - 'arn:aws:s3:::iiif-website'

functions:
  sitemap:
    handler: sitemap.update
    events:
        - httpApi:
            path: /
            method: post

plugins:
  - serverless-offline
  - serverless-python-requirements
